### ISSUE TITLE
error installing constantly : ERROR conda.core.link:_execute(481):

### ISSUE THREAD

**Issue by mayouf** [twisted/constantly#23]
Hi,

I tried to install SCRAPY by typing conda install scrapy

It gives an error with constantly. Then I tried to install constantly alone and I have an permission error:

`PermissionError(13, 'Permission denied')
`

Here is what I have when the terminal get stuck:

> mic@ubuntu:~$ conda install constantly
> Solving environment: done
>
>  Package Plan
>
>  environment location: /home/mic/anaconda3
>
> added / updated specs: 
>    constantly
>
>
>The following NEW packages will be INSTALLED:
>
>   constantly: 15.1.0-py36_0
>
>Proceed ([y]/n)? y
>
>Preparing transaction: done
>Verifying transaction: done
>Executing transaction: failed
>ERROR conda.core.link:_execute(481): An error occurred while installing package >defaults::constantly-15.1.0-py36_0'.
>PermissionError(13, 'Permission denied')
>Attempting to roll back.
>
>Rolling back transaction: done
>
>PermissionError(13, 'Permission denied')

Anyone can help me with this ??

**Comment by mayouf** [comment]
For the verbose output:

> mic@ubuntu:~$ conda install -v constantly
> Solving environment: ...working... done
> 
>  Package Plan 
> 
>   environment location: /home/mic/anaconda3
> 
>   added / updated specs: 
>     constantly
> 
> 
> The following NEW packages will be INSTALLED:
> 
>     constantly: 15.1.0-py36_0
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: ...working... done
> Verifying transaction: ...working... done
> Executing transaction: ...working... ===> LINKING PACKAGE: defaults::constantly-15.1.0-py36_0 <===
>   prefix=/home/mic/anaconda3
>   source=/home/mic/.conda/pkgs/constantly-15.1.0-py36_0
> 
> 
> ===> REVERSING PACKAGE LINK: defaults::constantly-15.1.0-py36_0 <===
>   prefix=/home/mic/anaconda3
> 
> 
> failed
> An error occurred while installing package 'defaults::constantly-15.1.0-py36_0'.
> PermissionError(13, 'Permission denied')
> Attempting to roll back.
> 
> 
> Rolling back transaction: ...working... done
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 535, in _execute_actions
>     action.execute()
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 364, in execute
>     force=context.force)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 280, in create_link
>     mkdir_p(dst)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
>     makedirs(path)
>   File "/home/mic/anaconda3/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/home/mic/anaconda3/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 472, in _execute
>     cls._execute_actions(pkg_idx, axngroup)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 553, in _execute_actions
>     reverse_excs,
> conda.CondaMultiError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 789, in __call__
>     return func(*args, **kwargs)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
>     exit_code = do_call(args, p)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
>     exit_code = getattr(module, func_name)(args, parser)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
>     install(args, parser, 'install')
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 255, in install
>     handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 285, in handle_txn
>     unlink_link_transaction.execute()
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 225, in execute
>     self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 500, in _execute
>     rollback_excs,
> conda.CondaMultiError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
>

**Comment by glyph** [comment]
This doesn't look like a problem with Constantly but some issue with Conda.

Please re-file if it's still happening with modern versions of stuff. Sorry we did not respond previously.
